### ISSUE TITLE
Building with visual studio 2013

### ISSUE THREAD

**Issue by fmiceli24** [catid/CauchyCaterpillar#1]
Hi. I am trying to build with VS 2013 and am having a problem with the static_assert in line 536 of PacketAllocator.h. "Assertion failed with too small"

I am building a real-time streaming solution and thought about adding CRS to it for error resiliency.

Also if I comment the static assert the project build correctly but then the test program fails in one of the recovery loops at a " sender.SendRecovery(recovery);"

Great work! Hope I can use it.

Thanks.

**Comment by fmiceli24** [comment]
Just fixed it. Commented the static assert and built under release. It now works as expected.

Do you think that I can run into issues due to building it with the 120 toolset?

Thanks again.

**Comment by catid** [comment]
I'll look into it.  I also need to update the CMakeLists.txt to build on other platforms

**Comment by catid** [comment]
Reproed the issue and fixed it.  Please let me know if I can help with anything else

**Comment by fmiceli24** [comment]
Thanks! It works!

Do you have a preferred (performant) way of serializing the Recovery packets for network transmission?

Thanks again.

**Comment by catid** [comment]
I left that as an open problem.  It depends a lot on the application.

If the application has a back-channel (e.g. acknowledging receipt of some data), then it's possible to compress the overhead a bit.  You can truncate each field to a number of low bytes, and then re-expand using this algorithm:

https://github.com/catid/StrikeRegister/blob/master/StrikeRegister.cpp#L143

If there is no back-channel then you can compress the fields to get rid of leading zeros.  So an encoding where the high/low bit means "more bytes are needed" and you stream in a byte or two at a time.  Example of that is here:

https://github.com/catid/siamese/blob/master/SiameseSerializers.h#L566

Otherwise you can still pick some reasonable upper-limit and make some assumptions and truncate to like 2-4 bytes.

uint64_t SequenceStart - Compressed as above

Data - No compression

Bytes - Can be implied by the frame it is in.  Otherwise it won't exceed 2 bytes

Count - 1 byte - Does not exceed 192.  You can use higher values like 255 to indicate an escape code to a different type of packet..

RecoveryRow - 1 byte (6 bits) - You can use the remaining 2 bits for something else like signaling it's an original versus recovery packet.

**Comment by catid** [comment]
In my reliable UDP library I compress all the fields to 1-3 bytes but it's a bunch of work to get right.  I'd just pick a fixed size and truncate..

**Comment by fmiceli24** [comment]
Excellent. Thanks for the detailed explanation and examples.

**Comment by fmiceli24** [comment]
Do you want me to close the issue or do you keep it open for some other reason?

**Comment by catid** [comment]
I should add this to the readme tonight and close it out

**Comment by fmiceli24** [comment]
Thanks!
